export interface AIProblemAnalysisRequest {
  challengeId?: string;
  title: string;
  description: string;
  category?: string;
  locationName?: string;
  state?: string;
  district?: string;
  city?: string;
  latitude?: number;
  longitude?: number;
  mediaUrls?: string[];
}

export interface AIProblemAnalysisResponse {
  language?: string;
  transcription?: string;
  translatedText?: string;
  problemSummary: string;
  category: string;
  subcategory?: string;
  severity: number; // 0-100
  urgency: number; // 0-100
  populationImpact?: string;
  healthImpact?: string;
  economicImpact?: string;
  aiConfidence: number; // 0.0 - 1.0
  duplicateProbability: number;
  recommendedDepartment?: string;
  recommendedUniversity?: string;
  recommendedExperts?: string[];
  recommendedIndustry?: string;
  matchedChallengeIds?: Array<{ id: string; similarityScore: number }>;
}

// 1. Health
export interface AIHealthResponse {
  status: 'healthy' | 'degraded' | 'offline';
  engineUrl: string;
  uptimeSeconds: number;
  activeModels: {
    nlpClassifier: string;
    severityEngine: string;
    matchingGNN: string;
    visionYOLO: string;
    speechWhisper: string;
    copilotLLM: string;
  };
  featuresAvailable: string[];
  systemLoad: {
    cpuPercent: number;
    memoryMb: number;
    gpuAcceleration: boolean;
  };
  timestamp: string;
}

// 2. Classification
export interface AIClassifyRequest {
  title: string;
  description: string;
  location?: string;
}

export interface AIClassifyResponse {
  primaryCategory: string;
  subcategory: string;
  confidence: number;
  sdgGoals: string[];
  tags: string[];
  sentiment: 'CRITICAL_CONCERN' | 'URGENT' | 'ROUTINE_MAINTENANCE' | 'COMMUNITY_PROPOSAL';
}

// 3. Severity
export interface AISeverityRequest {
  title: string;
  description: string;
  category?: string;
  affectedPopulation?: number;
  mediaUrls?: string[];
}

export interface AISeverityResponse {
  severityScore: number; // 0-100
  urgencyIndex: number; // 0-100
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  healthHazardScore: number;
  structuralRiskScore: number;
  recommendedSLA: string;
  reasoning: string;
}

// 4. Department Routing
export interface AIRouteRequest {
  title: string;
  description: string;
  category: string;
  city?: string;
  district?: string;
  state?: string;
}

export interface AIRouteResponse {
  primaryDepartment: string;
  nodalOfficer: string;
  escalationTier: 'Ward Level' | 'Zonal Level' | 'Municipal Commissionerate' | 'State Secretariat';
  slaHours: number;
  recommendedActionPlan: string[];
  estimatedBudgetRange: string;
}

// 5. Matching
export interface AIMatchRequest {
  challengeId?: string;
  category?: string;
  description?: string;
  problemDescription?: string;
  problem?: string;
  city?: string;
  state?: string;
  latitude?: number;
  longitude?: number;
}

export interface AIMatchResponse {
  matchedUniversities: Array<{
    id: string;
    name: string;
    city: string;
    state: string;
    matchScore: number;
    department: string;
    specialization: string;
  }>;
  matchedExperts: Array<{
    id: string;
    name: string;
    designation: string;
    universityName: string;
    matchScore: number;
    domain: string;
  }>;
  matchedIndustryPartners: Array<{
    id: string;
    organizationName: string;
    matchScore: number;
    csrFocus: string[];
    potentialFundingSlab: string;
  }>;
}

// 6. Vision
export interface AIVisionRequest {
  imageUrl?: string;
  imageBase64?: string;
  mediaUrls?: string[];
  image?: string;
  image_path?: string;
  mimeType?: string;
  mime_type?: string;
  title?: string;
  context?: string;
  description?: string;
}

export interface AIVisionResponse {
  visualVerificationStatus: 'VERIFIED_DAMAGE' | 'INCONCLUSIVE' | 'IRRELEVANT_IMAGE' | 'VERIFIED_AUTHENTIC_DAMAGE' | 'UNAUTHENTIC_OR_MISMATCH';
  isAuthentic?: boolean;
  authenticityScore?: number;
  matchesDescription?: boolean;
  matchExplanation?: string;
  isPrioritized?: boolean;
  warningMessage?: string | null;
  defectSeverity: number;
  damageSeverity?: string;
  suggestedCategory?: string;
  recommendation?: string;
  detectedDefects: string[];
  boundingPredictions: Array<{
    label: string;
    confidence: number;
    box: [number, number, number, number];
  }>;
  estimatedDimensions: string;
  aiNotes: string;
}

// 7. Voice
export interface AIVoiceRequest {
  audioUrl?: string;
  audioBase64?: string;
  languageHint?: string;
}

export interface AIVoiceResponse {
  transcribedText: string;
  detectedLanguage: string;
  confidence: number;
  extractedEntities: {
    location?: string;
    problemType?: string;
    urgency?: string;
  };
  autoGeneratedTitle: string;
}

// 8. Impact
export interface AIImpactRequest {
  title?: string;
  category?: string;
  proposedSolution?: string;
  problemDescription?: string;
  estimatedBudget?: number;
  targetPopulation?: number;
}

export interface AIImpactResponse {
  socialReturnOnInvestment: string;
  beneficiaryReach: string;
  carbonReductionMetric: string;
  sdgImpactScores: Record<string, number>;
  riskMitigationScore: number;
  feasibilityIndex: number;
  executiveSummary: string;
}

// 9. Trends
export interface AITrendRequest {
  state?: string;
  district?: string;
  category?: string;
  timeWindowDays?: number;
}

export interface AITrendResponse {
  timeWindowDays: number;
  totalAnalyzed: number;
  identifiedHotspots: Array<{
    location: string;
    incidentCount: number;
    dominantCategory: string;
    riskLevel: 'HIGH' | 'CRITICAL' | 'ELEVATED';
  }>;
  emergingTrends: Array<{
    trendName: string;
    category: string;
    growthRatePercent: number;
    description: string;
  }>;
  predictiveAlerts: string[];
}

// 10. Spam & Fake Check
export interface AISpamCheckRequest {
  title: string;
  description: string;
  imageUrl?: string;
  reporterId?: string;
}

export interface AISpamCheckResponse {
  isSpam: boolean;
  isFake: boolean;
  credibilityScore: number; // 0-100%
  verificationStatus: 'GENUINE_CIVIC_REPORT' | 'NEEDS_VERIFICATION' | 'FLAGGED_SPAM';
  flags: string[];
  recommendation: 'APPROVE' | 'REQUIRE_MANUAL_REVIEW' | 'REJECT';
}

// 11. Report Generator
export interface AIReportGenerateRequest {
  reportType: 'WARD_BRIEFING' | 'CSR_AUDIT' | 'EXECUTIVE_SUMMARY' | 'PILOT_EVALUATION';
  district?: string;
  category?: string;
  dateRange?: { start?: string; end?: string };
}

export interface AIReportGenerateResponse {
  reportId: string;
  reportType: string;
  generatedAt: string;
  title: string;
  markdownContent: string;
  kpiHighlights: Record<string, string | number>;
  actionItems: string[];
}

// 12. Project Copilot
export interface AICopilotChatRequest {
  query: string;
  role?: string;
  context?: Record<string, unknown>;
  conversationHistory?: Array<{ role: 'user' | 'assistant' | 'system'; content: string }>;
}

export interface AICopilotChatResponse {
  answer: string;
  suggestedFollowUps?: string[];
  actionableLinks?: Array<{ label: string; url: string }>;
  groundingSources?: string[];
}

