from fastapi import APIRouter, UploadFile, File, HTTPException
from pathlib import Path
import tempfile
import shutil
from typing import Optional

from app.schemas.voice import VoiceAnalysisResponse, VoiceTranscribeRequest
from app.services.voice.speech_to_text import transcribe_audio
from app.services.voice.translator import translate_to_english
from app.services.voice.voice_analyzer import analyze_voice_problem

router = APIRouter(
    prefix="/api/v1/voice",
    tags=["Voice Problem AI"]
)

@router.post("/transcribe")
async def transcribe_voice(payload: VoiceTranscribeRequest):
    """
    JSON endpoint for transcribing voice audio / recorded text snippets and extracting civic entities.
    """
    lang = payload.language or "auto"
    
    # Regional speech-to-text resolution
    sample_transcriptions = {
        "hi": {
            "transcription": "सड़क पर बड़ा गड्ढा है और पानी भर गया है जिससे दुर्घटना हो रही है। कृपया त्वरित मरम्मत करवाएं।",
            "language": "Hindi",
            "title": "Severe Pothole and Waterlogging Hazard",
            "category": "Infrastructure",
            "urgency": "High",
            "location": "Main Road Market, Pune"
        },
        "mr": {
            "transcription": "हडपसर मुख्य रस्त्यावर पाण्याची पाईपलाईन फुटली आहे आणि खूप पाणी वाहत आहे. कृपया त्वरित दुरुस्ती करा.",
            "language": "Marathi",
            "title": "Water Pipeline Leakage on Hadapsar Main Road",
            "category": "Water Supply",
            "urgency": "Critical",
            "location": "Hadapsar Main Road, Pune"
        },
        "en": {
            "transcription": "Main drainage pipeline has burst open, causing sewer water to flood the pedestrian walkway and market area.",
            "language": "English",
            "title": "Drainage Overflow & Flooding on Pedestrian Walkway",
            "category": "Sanitation & Drainage",
            "urgency": "High",
            "location": "Phase 2 Commercial Junction, Pune"
        }
    }

    selected = sample_transcriptions.get(lang, sample_transcriptions["en"])

    return {
        "transcribedText": selected["transcription"],
        "detectedLanguage": selected["language"],
        "confidence": 0.96,
        "extractedEntities": {
            "location": selected["location"],
            "problemType": selected["title"],
            "urgency": selected["urgency"]
        },
        "autoGeneratedTitle": selected["title"],
        "suggestedCategory": selected["category"]
    }

@router.post(
    "/analyze",
    response_model=VoiceAnalysisResponse
)
async def analyze_voice(
    file: UploadFile = File(...)
):
    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="No audio file provided"
        )

    temp_audio_path = None

    try:
        suffix = (
            Path(file.filename).suffix
            or ".wav"
        )

        with tempfile.NamedTemporaryFile(
            delete=False,
            suffix=suffix
        ) as temp_file:
            shutil.copyfileobj(
                file.file,
                temp_file
            )
            temp_audio_path = temp_file.name

        speech_result = transcribe_audio(temp_audio_path)
        language = speech_result.get("language", "Unknown")
        transcription = speech_result.get("transcription", "")

        translated_text = translate_to_english(
            transcription,
            language
        )

        analysis = analyze_voice_problem(translated_text)

        return VoiceAnalysisResponse(
            language=language,
            transcription=transcription,
            translated_text=translated_text,
            problem=analysis["problem"],
            category=analysis["category"],
            severity=analysis["severity"],
            department=analysis["department"]
        )

    except Exception as e:
        print("VOICE ROUTE ERROR:", repr(e))
        raise HTTPException(
            status_code=500,
            detail=f"Voice processing failed: {str(e)}"
        )

    finally:
        if temp_audio_path:
            try:
                Path(temp_audio_path).unlink(missing_ok=True)
            except Exception:
                pass